language: python
sudo: enabled
python:
  - 3.6

matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
    - language: python
      os: linux
      before_install:
        - sudo apt-get update -qq

install:
  - pip3 install ansible

script:
  - make test-ci
