
- name: install fzf
  shell: '{{playbook_dir}}/../cooker-proj/commandos/install-fzf.sh'
  when: ansible_os_family == 'Debian'

- name: install fzf for Mac OS X
  homebrew: name=fzf state=present
  when: ansible_os_family == 'Darwin'
