- name: apt_key:yarn
  become: true
  when: ansible_os_family == 'Debian'
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: packages:ubuntu
  package: name={{item}} state=present
  when: ansible_os_family == 'Debian'
  become: true
  with_items:
    - lsof
    - tree
    - yarn
    - silversearcher-ag
    - git
    - python-dev
    - python3-dev
    - cmake
    - htop
    - bash-completion
