- debug:
    msg: "aliases: {{aliases|to_nice_yaml}}"

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh


- name: install zsh on ubuntu step2
  when: ansible_os_family == 'Debian'
  become: true
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: make sure rice gets loaded for bash and zsh
  lineinfile:
    path: ~/.{{item}}rc
    line: "[ -f ~/.rice.bash ] && source ~/.rice.{{item}}"
  with_items:
    - bash
    - zsh

- name: insert fzf into zshrc
  lineinfile:
    create: true
    path: ~/.zshrc
    line: '[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh'


- name: insert a line into bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: '[ -f ~/.bashrc ] && source ~/.bashrc'
    create: yes

- name: write ~/.rice.bash
  vars:
    rice_type: bash
  template:
    src: '{{role_path}}/files/rice-shell.template.sh'
    dest: ~/.rice.bash

- name: write ~/.rice.zsh
  vars:
    rice_type: zsh
  template:
    src: '{{role_path}}/files/rice-shell.template.sh'
    dest: ~/.rice.zsh
