- name: install the_silver_searcher for Mac OS X
  homebrew: name=the_silver_searcher state=present
  when: ansible_os_family == 'Darwin'

- name: sync agignore
  file:
      src: '{{role_path}}/files/ag/agignore'
      dest: '~/.agignore'
      state: link
      force: yes

