# File directory roles/common/files

- name: sync tmux config
  file:
      src: '{{role_path}}/files/tmux/{{item}}'
      dest: '~/.{{item}}'
      state: link
      force: yes
  with_items:
    - tmux.conf
    - tmux.conf.local
