- file:
    path: ~/.vim/backups
    state: directory

- file:
    path: ~/.vim/swaps
    state: directory

- name: install vim for Mac OS X
  homebrew: name=vim state=present
  when: ansible_os_family == 'Darwin'

- name: install vim for Ubuntu
  when: ansible_os_family == 'Debian'
  shell: '{{playbook_dir}}/../cooker-proj/commandos/compile-vim8-debian-python3.sh'
  become: true

- name: install vim plug
  shell: '{{playbook_dir}}/../cooker-proj/commandos/install-vim-plug.sh'

- name: symlimk vimrc
  file:
      src: '{{role_path}}/files/vim/vimrc'
      dest: '~/.vimrc'
      state: link
      force: yes

- name: verify vim 8.2 is installed
  shell: "vim --version | grep '8.2'"
  args:
    executable: /bin/bash
