- name: insert a line into bashrc
  lineinfile:
    path: ~/.bashrc
    line: '[ -f ~/.rice.bash ] && source ~/.rice.bash'


- name: insert a line into bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: '[ -f ~/.bashrc ] && source ~/.bashrc'
    create: yes

- name: write rice.bash
  template:
    src: '{{playbook_dir}}/roles/common/files/rice.template.bash'
    dest: ~/.rice.bash
