
# - name: symlimk bash profile
#   file:
#       src: '{{playbook_dir}}/configurations/bash/bash_profile.bash'
#       dest: '~/.bash_profile'
#       state: link
#       force: yes



- name: insert a line into bashrc
  lineinfile:
    path: ~/.bashrc
    line: '[ -f ~/.rice.bash ] && source ~/.rice.bash'


    # - name: insert blocks into rice.bash
    #   blockinfile:
    #     block: "{{lookup('file', 'rice.bash.template')}}"
    #     path: ~/.bashrc
    #
    #
    #

- name: write rice.bash
  template:
    src: '{{playbook_dir}}/roles/common/files/rice.template.bash'
    dest: ~/.rice.bash
