---
# This playbook contains common plays that will be run on all nodes.

- debug: msg="{{ansible_os_family}}"

- name: install the_silver_searcher
  package: name=the_silver_searcher state=present

- name: install git
  package: name=git state=present

- name: sync git config
  template:
      src: './configurations/git/gitconfig'
      dest: '~/.gitconfig'
  tags:
    - rc_files

- name: sync vimrc
  file:
      src: '~/docs/configurations/vim/vimrc'
      dest: '~/.vimrc'
      state: link
      force: yes

  tags:
    - vim
    - rc_files


