---
# This playbook contains common plays that will be run on all nodes.

- debug:
    msg: "Operating system is {{ansible_os_family}}. Current directory: {{playbook_dir}}. Python version is {{ansible_playbook_python}}"

- include: the_silver_searcher.yml
  tags: the_siver_searcher

- include: vim.yml
  tags: vim

- include: git.yml
  tags: git

- include: bash.yml
  tags: bash

- include: tmux.yml
  tags: tmux

- include: fzf.yml
  tags: fzf

- include: zed.yml
  tags: zed

- include: other_tools.yml
  tags: other_tools
