---
# This playbook contains common plays that will be run on all nodes.

- debug:
    msg: "Operating system is {{ansible_os_family}}. Current directory: {{playbook_dir}}"

- name: install the_silver_searcher for Mac OS X
  homebrew: name=the_silver_searcher state=present
  when: ansible_os_family == 'Darwin'

- name: install the_silver_searcher for Ubuntu
  package: name=silversearcher-ag state=present
  when: ansible_os_family == 'Debian'
  become: true

- name: install git
  package: name=git state=present

- name: sync git config
  file:
      src: '{{playbook_dir}}/configurations/git/gitconfig'
      dest: '~/.gitconfig'
      state: link
      force: yes
  tags:
    - rc_files

- name: symlimk vimrc
  file:
      src: '{{playbook_dir}}/configurations/vim/vimrc'
      dest: '~/.vimrc'
      state: link
      force: yes

  tags:
    - vim
    - rc_files


