---
# This playbook contains common plays that will be run on all nodes.

- debug: msg="{{ansible_os_family}}"

- name: install the_silver_searcher for Mac OS X
  homebrew: name=the_silver_searcher state=present
  when: ansible_os_family == 'Darwin'

- name: install the_silver_searcher for Ubuntu
  package: name=silversearcher-ag state=present
  when: ansible_os_family == 'Debian'
  become: true

- name: install git
  package: name=git state=present

- name: sync git config
  template:
      src: './configurations/git/gitconfig'
      dest: '~/.gitconfig'
  tags:
    - rc_files

- name: symlimk vimrc
  file:
      src: '~/docs/configurations/vim/vimrc'
      dest: '~/.vimrc'
      state: link
      force: yes

  tags:
    - vim
    - rc_files


