---
# This playbook contains common plays that will be run on all nodes.

- debug:
    msg: "Operating system is {{ansible_os_family}}. Current directory: {{playbook_dir}}. Python version is {{ansible_playbook_python}}"

- include: the_silver_searcher.yml
  tags: the_siver_searcher

- include: shell.yml
  tags: shell

- include: vim.yml
  tags: vim

- include: git.yml
  tags: git

- include: tmux.yml
  tags: tmux

- include: fzf.yml
  tags: fzf

- include: zed.yml
  tags: zed

- include: packages.yml
  tags: packages

- include: docker.yml
  tags:
    - docker
    - skip-ci
