- name: install lsof
  package: name=lsof state=present
  when: ansible_os_family == 'Debian'
  become: true

- name: install tree
  package: name=tree state=present
  when: ansible_os_family == 'Debian'
  become: true

- name: add apt-key for yarn
  become: true
  when: ansible_os_family == 'Debian'
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: add apt repository for yarn
  become: true
  when: ansible_os_family == 'Debian'
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: install yarn
  package: name=yarn state=present
  when: ansible_os_family == 'Debian'
  become: true

- name: add apt-key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: add apt repository for docker
  become: true
  when: ansible_os_family == 'Debian'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install docker
  package: name=docker-ce state=present update_cache=yes
  when: ansible_os_family == 'Debian'
  become: true

- name: add user "{{ansible_user}}" to docker group
  become: true
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes
