- name: install the_silver_searcher for Mac OS X
  homebrew: name=the_silver_searcher state=present
  when: ansible_os_family == 'Darwin'

- name: install the_silver_searcher for Ubuntu
  package: name=silversearcher-ag state=present
  when: ansible_os_family == 'Debian'
  become: true

- name: sync agignore
  file:
      src: '{{playbook_dir}}/configurations/ag/agignore'
      dest: '~/.agignore'
      state: link
      force: yes

