
- name: install vim for Mac OS X
  homebrew: name=vim state=present install_options=--with-python3
  when: ansible_os_family == 'Darwin'

- name: install vim for Ubuntu
  when: ansible_os_family == 'Debian'
  shell: '{{playbook_dir}}/compile-vim.sh python3'
  become: true

- name: symlimk vimrc
  file:
      src: '{{playbook_dir}}/configurations/vim/vimrc'
      dest: '~/.vimrc'
      state: link
      force: yes

- name: verify vim is installed
  shell: (vim --version | grep '8.0') && (vim --version | grep '+python3')
