
- name: install vim for Mac OS X
  homebrew: name=vim state=present install_options=--with-python3
  when: ansible_os_family == 'Darwin'

- name: install vim for Ubuntu
  when: ansible_os_family == 'Debian'
  shell: '{{playbook_dir}}/bin/compile-vim8-debian-python3.sh'
  become: true

- name: install vim plug
  shell: '{{playbook_dir}}/bin/install-vim-plug.sh'

- name: symlimk vimrc
  file:
      src: '{{playbook_dir}}/configurations/vim/vimrc'
      dest: '~/.vimrc'
      state: link
      force: yes

- name: verify vim 8.0 is installed
  shell: "vim --version | grep '8.0'"
  args:
    executable: /bin/bash
