if &compatible
    set nocompatible
endif
set runtimepath+=~/.vim/bundles/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.vim/bundles')
    call dein#begin('~/.vim/bundles')

    " Let dein manage dein
    " Required:
    call dein#add('~/.vim/bundles/repos/github.com/Shougo/dein.vim')

    " Add or remove your plugins here:
    call dein#add('Shougo/neosnippet.vim')
    call dein#add('Shougo/neosnippet-snippets')

    " You can specify revision/branch/tag.
    call dein#add('Shougo/vimshell', { 'rev': '3787e5' })
    call dein#add('scrooloose/nerdtree')
    call dein#add('jonathanfilip/vim-lucius')
    call dein#add('kien/ctrlp.vim')
    call dein#add('klen/python-mode')
    call dein#add('scrooloose/syntastic')
    call dein#add('vim-airline/vim-airline')
    call dein#add('vim-airline/vim-airline-themes')
    call dein#add('mileszs/ack.vim')
    call dein#add('digitaltoad/vim-jade')
    call dein#add('pangloss/vim-javascript')
    call dein#add('maksimr/vim-jsbeautify')
    call dein#add('ervandew/supertab')
    call dein#add('saltstack/salt-vim')
    call dein#add('schickling/vim-bufonly')
    call dein#add('alvan/vim-closetag')
    call dein#add('elzr/vim-json')
    call dein#add('mxw/vim-jsx')
    call dein#add('editorconfig/editorconfig-vim')
    call dein#add('jparise/vim-graphql')

    " NeoBundleLazy 'flowtype/vim-flow', {
    "             \ 'autoload': {'filetypes': 'javascript'},
    "             \}

    " NeoBundle 'jiangmiao/auto-pairs'

    " Required:
    call dein#end()
    call dein#save_state()
endif

filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif



 " Toggle nerd tree
 map <C-n> :NERDTreeToggle<CR>
 let NERDTreeIgnore = ['__pycache__', 'node_modules']

 " Auto reload vimrc
 autocmd! bufwritepost .vimrc source %

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file
endif
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let &guioptions = substitute(&guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
"if has('mouse')
"  set mouse=a
"endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else

  set autoindent		" always set autoindenting on

endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

" Customized section
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
au BufNewFile,BufRead *.mako set filetype=html

set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

set number
set ignorecase
set smartcase
set background=dark

" Disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
imap <C-h> <Left>
imap <C-j> <Down>
imap <C-k> <Up>
imap <C-l> <Right>

" Use shift-H and shift-L to change buffer
nmap H :bp<CR>
nmap L :bn<CR>
nmap <C-f> :Ack<Space>

" Use fuzzy finder buffer mode to open buffer
map <Leader>d :CtrlP .<CR>
map <Leader>f :CtrlPBuffer<CR>
set wildignore+=*/coverage/*,*/build/*,*/node_modules/*,*/__pycache__/*,*.ttf,*.svg,*.pyc,*/build-debug/*,venv/*
" map <Leader>d :FufFileWithCurrentBufferDir<CR>

" close buffer without closing the window
nmap <Leader>q :bp<bar>sp<bar>bn<bar>bd<CR>
imap <Leader>w <ESC>:w<CR>
nmap <Leader>w <ESC>:w<CR>
imap zz <ESC>

" set tags files
set tags=tags;


" pyflakes
let g:pyflakes_use_quickfix = 0


" pymode settings
" filetype off
" call pathogen#infect()
" call pathogen#helptags()
" filetype plugin indent on
" syntax on

let g:pymode_rope_goto_definition_bind = '<F3>'
let g:pymode_rope_goto_definition_cmd = 'e'
let g:pymode_rope_complete_on_dot = 0
" Do not let pymode automatically fold
let g:pymode_folding = 1
set foldlevel=1

" Do not let pymode auto fix whitespaces
let g:pymode_utils_whitespaces = 0

let g:pymode_lint_write = 0

let g:pymode_lint_checkers = '[pyflakes,mccabe]'


" DO NOT Auto open cwindow if errors be finded
let g:pymode_lint_cwindow = 0

" Supertab
imap <tab> <C-Space>
let g:SuperTabDefaultCompletionType = "<c-n>"
let g:SupertabDefaultCompletionType = "context"
let g:SuperTabClosePreviewOnPopupClose = 1
set completeopt=menuone,longest,preview

" This auto close preview window if you exit the insert mode
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

set backupdir=~/.vim/backups
set directory=~/.vim/swaps

set wildmode=longest:full,list
let g:syntastic_python_checkers = ['flake8']
set t_Co=256

set relativenumber
set cursorcolumn
colorscheme lucius

" run unittest
nmap <Leader>t :!python3 manage.py test <cword>

" close all buffers but current
nmap <Leader>c :BufOnly<CR>


" Airline settings
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='papercolor'
let g:airline_powerline_fonts = 1
set laststatus=2


au BufNewFile,BufRead *.styl set filetype=less

" closetag filename extensions
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.ts,*jsx,*js"

" clip command to copy yanked text to a file served by ngxin
command! CP :w! /usr/share/nginx/html/clips/1.txt

" typescript
"let g:typescript_compiler_binary = './node_modules/.bin/tsc'
"let g:typescript_compiler_options = ''
autocmd FileType typescript :set makeprg=./node_modules/.bin/tsc
set backupcopy=yes

let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exec = './node_modules/.bin/eslint'

" JSX works for .js files
let g:jsx_ext_required = 0

" Automatically remove trailing whitespace
autocmd BufWritePre * %s/\s\+$//e

" Dsiabling rope autoimport for performance reasons
let g:pymode_rope_autoimport = 0
let g:pymode_rope_regenerate_on_write = 0

" FZF
set rtp+=~/.fzf

" Use ag instead of ack
" let g:ackprg = 'ag --nogroup --nocolor --column'
let g:ackprg = 'git grep -n'

